import { type ReactNode } from "react";
import Head from "next/head";
import Navbar from "src/components/Navbar";

export default function Main ({
  isSearcher,
  children
}: {
  isSearcher?: boolean,
  children: ReactNode
}) {
  return (
    <>
      <Head>
        <title>Searchers</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col h-screen">
        <Navbar isSearcher={isSearcher} />
        <div className="grow h-4/5">
          {children}
        </div>
      </div>
    </>
  )
}
